---
- hosts: servers
  become: yes
  become_user: root
  vars_files:
    - vars/vars.yaml
  roles:
    - tools
    - docker
    - home-assistant
    - retropie
  handlers:
    - include: handlers/main.yml